# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\barry\Desktop\opencv_and_deep_learning\hw2_E94061076\hw2_E94061076.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Find_contour
import Camera_Calibration
import Augmented_Reality
import Stereo_Disparity_Map
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        #Group1
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox) ### button for 1.1 draw Contour
        self.pushButton.setObjectName("pushButton")            ###
        self.verticalLayout.addWidget(self.pushButton)         ###
        self.pushButton.clicked.connect(self.Draw_Contour)  ##執行1.1
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox) ### button for 1.2 Count Contour
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_2.clicked.connect(self.Count_Contour)  ##執行1.2
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 2, 1)
        #Group3
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.gridLayout.addWidget(self.groupBox_4, 0, 1, 1, 1)
        #self.sub_window = SubWindow()
        #self.pushButton_7.clicked.connect(self.sub_window.show)
        self.pushButton_7.clicked.connect(self.augmented_reality)
        #Group4
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.gridLayout.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.pushButton_8.clicked.connect(self.stereo_disparity_map)
        #Group2
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2) #2.1 Find Corner
        self.pushButton_3.setObjectName("pushButton_3")            #
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 0, 1, 1) # 
        self.pushButton_3.clicked.connect(self.Find_corner)        #
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)          ##在第二題介面中再加一個Groupˇ
        self.groupBox_3.setObjectName("groupBox_3")                     ##
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)  ##
        self.verticalLayout_2.setObjectName("verticalLayout_2")         ##
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)        ###Group3中的label - Select image     
        self.label_3.setObjectName("label_3")                   ###
        self.verticalLayout_2.addWidget(self.label_3)           ###

        choices = [str(x) for x in range (1,15)]                        ####Group3中的combobox
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)            ####
        self.comboBox.setObjectName("comboBox")                         ####
        self.verticalLayout_2.addWidget(self.comboBox)                  ####
        self.comboBox.addItems(choices)                                 ####

        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)  #####Group3中的button - 2.3 Extrinsic matirx
        self.pushButton_6.setObjectName("pushButton_6")             #####
        self.verticalLayout_2.addWidget(self.pushButton_6)          #####
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 3, 1)    #####
        self.pushButton_6.clicked.connect(self.Find_Extrinsic)      #####
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)  ######Group2中的Button - 2.2 Find Intrinsic
        self.pushButton_4.setObjectName("pushButton_4")             ######
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 0, 1, 1)  ######
        self.pushButton_4.clicked.connect(self.Find_Intrinsic)      ######
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)  #######Group2中的Button - 2.4 Find Distortoin
        self.pushButton_5.setObjectName("pushButton_5")             #######
        self.gridLayout_2.addWidget(self.pushButton_5, 2, 0, 1, 1)  #######
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 2)      #######
        self.pushButton_5.clicked.connect(self.Find_distortion)     #######

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "1. Find Contour"))
        self.pushButton.setText(_translate("MainWindow", "1.1 Draw Contour"))
        self.pushButton_2.setText(_translate("MainWindow", "1.2 Count Contour"))
        self.label.setText(_translate("MainWindow", "There are _ coins in Coin01.jpg"))
        self.label_2.setText(_translate("MainWindow", "There are _ coins in Coin02.jpg"))
        self.groupBox_4.setTitle(_translate("MainWindow", "3. Augmented Reality"))
        self.pushButton_7.setText(_translate("MainWindow", "3.1 Augmented Reality"))
        self.groupBox_5.setTitle(_translate("MainWindow", "4. Stereo Disparity Map"))
        self.pushButton_8.setText(_translate("MainWindow", "4.1 Stereo Disparity Map"))
        self.groupBox_2.setTitle(_translate("MainWindow", "2. Calibration"))
        self.pushButton_3.setText(_translate("MainWindow", "2.1 Find Corners"))
        self.groupBox_3.setTitle(_translate("MainWindow", "2.3 Find Extrinsic"))
        self.label_3.setText(_translate("MainWindow", "Select image"))
        self.pushButton_6.setText(_translate("MainWindow", "2.3 Find Extrinsic"))
        self.pushButton_4.setText(_translate("MainWindow", "2.2 Find Intrinsic"))
        self.pushButton_5.setText(_translate("MainWindow", "2.4 Find Distortion"))

    def Draw_Contour(self):
        Find_contour.draw_contours()
    def Count_Contour(self , MainWindow):
        _translate = QtCore.QCoreApplication.translate
        num01 , num02 = Find_contour.count_contours()
        self.label.setText(_translate("MainWindow", "There are " + str(num01) + " coins in Coin01.jpg"))
        self.label_2.setText(_translate("MainWindow", "There are " + str(num02) + " coins in Coin01.jpg"))
    
    def Find_corner(self) :
        Camera_Calibration.find_corners()
    def Find_Intrinsic(self) :
        Camera_Calibration.find_intrinsic()
    def Find_Extrinsic(self) :
        number = self.comboBox.currentText()  
        Camera_Calibration.find_extrinsic(int(number))
    def Find_distortion(self) :
        Camera_Calibration.find_distortion()
    
    def augmented_reality(self) :
        Augmented_Reality.augmented_reality()

    def stereo_disparity_map(self):
        Stereo_Disparity_Map.stereo_disparity_map()
if __name__ == '__main__':  
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()

    ui.setupUi(MainWindow) 
    MainWindow.show()
    sys.exit(app.exec_()) 